const KET_WORDS_A = [
  {w:"a/an",ph:"/ə/",p:"art.",m:"一个",col:"a book / an apple",ex:"I have a book. / She is an artist.",sy:"a",tip:"a用于辅音前，an用于元音前"},
  {w:"about",ph:"/əˈbaʊt/",p:"prep./adv.",m:"关于；大约",col:"about time / talk about",ex:"Tell me about your school.",sy:"a-bout",tip:"about=ab(加强)+out(向外)"},
  {w:"above",ph:"/əˈbʌv/",p:"prep.",m:"在…上面",col:"above the desk",ex:"The clock is above the door.",sy:"a-bove",tip:"反义词：below"},
  {w:"across",ph:"/əˈkrɒs/",p:"prep.",m:"穿过；横过",col:"across the road",ex:"Walk across the street.",sy:"a-cross",tip:"cross=十字路口"},
  {w:"act",ph:"/ækt/",p:"v.",m:"行动；扮演",col:"act out / act like",ex:"Act like a teacher.",pt:"acted",sy:"act",tip:"actor=男演员"},
  {w:"add",ph:"/æd/",p:"v.",m:"添加；加",col:"add to / add up",ex:"Add some water to the cup.",pt:"added",sy:"add",tip:"addition=加法"},
  {w:"afraid",ph:"/əˈfreɪd/",p:"adj.",m:"害怕的",col:"be afraid of",ex:"Don't be afraid of dogs.",sy:"a-fraid",tip:"fraid像fright(惊吓)"},
  {w:"after",ph:"/ˈɑːftə/",p:"prep.",m:"在…之后",col:"after school",ex:"Let's play after school.",sy:"af-ter",tip:"反义词：before"},
  {w:"again",ph:"/əˈɡen/",p:"adv.",m:"再次",col:"try again / see you again",ex:"Please say it again.",sy:"a-gain",tip:"gain=获得，再获得一次"},
  {w:"age",ph:"/eɪdʒ/",p:"n.",m:"年龄",col:"at the age of",ex:"She is seven years of age.",sy:"age",tip:"age=年纪"},
  {w:"ago",ph:"/əˈɡəʊ/",p:"adv.",m:"以前",col:"long ago / two days ago",ex:"I saw him a week ago.",sy:"a-go",tip:"go=去，已经过去了"},
  {w:"agree",ph:"/əˈɡriː/",p:"v.",m:"同意",col:"agree with / agree to",ex:"I agree with you.",pt:"agreed",sy:"a-gree",tip:"反义词：disagree"},
  {w:"air",ph:"/eə/",p:"n.",m:"空气",col:"fresh air / by air",ex:"The air is fresh.",sy:"air",tip:"airport=机场"},
  {w:"all",ph:"/ɔːl/",p:"adj./adv.",m:"全部；所有",col:"all day / all the time",ex:"All the children are happy.",sy:"all",tip:"a-ll, 所有"},
  {w:"also",ph:"/ˈɔːlsəʊ/",p:"adv.",m:"也；还",col:"also like / also have",ex:"I also like cats.",sy:"al-so",tip:"also=也，放在句中"},
  {w:"always",ph:"/ˈɔːlweɪz/",p:"adv.",m:"总是",col:"always late / always happy",ex:"She always smiles.",sy:"al-ways",tip:"al(l)+ways(方式)=总是"},
  {w:"among",ph:"/əˈmʌŋ/",p:"prep.",m:"在…之中",col:"among friends",ex:"She is popular among classmates.",sy:"a-mong",tip:"among用于三者以上"},
  {w:"and",ph:"/ænd/",p:"conj.",m:"和；并且",col:"you and me / read and write",ex:"I like cats and dogs.",sy:"and",tip:"最常用的连词"},
  {w:"angry",ph:"/ˈæŋɡri/",p:"adj.",m:"生气的",col:"be angry with",ex:"Don't be angry with me.",sy:"an-gry",tip:"angry=anger+y"},
  {w:"animal",ph:"/ˈænɪml/",p:"n.",m:"动物",col:"wild animal / pet animal",ex:"I love animals.",sy:"an-i-mal",tip:"ani+mal=动物"},
  {w:"another",ph:"/əˈnʌðə/",p:"adj./pron.",m:"另一个",col:"another one / another cup",ex:"Have another cake.",sy:"an-oth-er",tip:"an+other=另一个"},
  {w:"answer",ph:"/ˈɑːnsə/",p:"v./n.",m:"回答；答案",col:"answer the question",ex:"Please answer my question.",pt:"answered",sy:"an-swer",tip:"反义词：ask"},
  {w:"any",ph:"/ˈeni/",p:"adj./pron.",m:"任何；一些",col:"any time / any questions",ex:"Do you have any pens?",sy:"a-ny",tip:"多用于疑问句和否定句"},
  {w:"appear",ph:"/əˈpɪə/",p:"v.",m:"出现",col:"appear on TV",ex:"A rabbit appeared from the hat.",pt:"appeared",sy:"ap-pear",tip:"反义词：disappear"},
  {w:"apple",ph:"/ˈæpl/",p:"n.",m:"苹果",col:"apple juice / apple pie",ex:"I eat an apple every day.",sy:"ap-ple",tip:"An apple a day keeps the doctor away."},
  {w:"April",ph:"/ˈeɪprəl/",p:"n.",m:"四月",col:"in April / April Fool's Day",ex:"My birthday is in April.",sy:"A-pril",tip:"Apr是缩写"},
  {w:"arm",ph:"/ɑːm/",p:"n.",m:"手臂",col:"arm in arm / take one's arm",ex:"She hurt her arm.",sy:"arm",tip:"armchair=扶手椅"},
  {w:"around",ph:"/əˈraʊnd/",p:"prep./adv.",m:"在…周围；大约",col:"walk around / around 5 o'clock",ex:"There are trees around the house.",sy:"a-round",tip:"round=圆形的"},
  {w:"arrive",ph:"/əˈraɪv/",p:"v.",m:"到达",col:"arrive at / arrive in",ex:"We arrived at school at 8.",pt:"arrived",sy:"ar-rive",tip:"arrive at+小地方，in+大地方"},
  {w:"ask",ph:"/ɑːsk/",p:"v.",m:"问；请求",col:"ask a question / ask for",ex:"May I ask a question?",pt:"asked",sy:"ask",tip:"反义词：answer"},
  {w:"August",ph:"/ˈɔːɡəst/",p:"n.",m:"八月",col:"in August",ex:"August is very hot.",sy:"Au-gust",tip:"Aug是缩写"},
  {w:"aunt",ph:"/ɑːnt/",p:"n.",m:"阿姨；姑妈",col:"Aunt Mary / my aunt",ex:"My aunt lives in London.",sy:"aunt",tip:"uncle=叔叔/舅舅"},
  {w:"autumn",ph:"/ˈɔːtəm/",p:"n.",m:"秋天",col:"in autumn / autumn leaves",ex:"Leaves fall in autumn.",sy:"au-tumn",tip:"fall=秋天（美式）"},
  {w:"away",ph:"/əˈweɪ/",p:"adv.",m:"离开；远离",col:"go away / run away",ex:"The cat ran away.",sy:"a-way",tip:"way=路，away=离开"},
  {w:"baby",ph:"/ˈbeɪbi/",p:"n.",m:"婴儿",col:"baby boy / cry like a baby",ex:"The baby is sleeping.",sy:"ba-by",tip:"babysitter=保姆"},
  {w:"back",ph:"/bæk/",p:"n./adv.",m:"背部；回来",col:"come back / go back",ex:"I will come back soon.",sy:"back",tip:"反义词：front"},
  {w:"bad",ph:"/bæd/",p:"adj.",m:"坏的；糟糕的",col:"bad weather / be bad at",ex:"I'm bad at singing.",sy:"bad",tip:"比较级 worse, 最高级 worst"},
  {w:"bag",ph:"/bæɡ/",p:"n.",m:"包；袋子",col:"school bag / paper bag",ex:"My bag is blue.",sy:"bag",tip:"handbag=手提包"},
  {w:"ball",ph:"/bɔːl/",p:"n.",m:"球",col:"play ball / throw a ball",ex:"The ball is round.",sy:"ball",tip:"football=足球，basketball=篮球"},
  {w:"banana",ph:"/bəˈnɑːnə/",p:"n.",m:"香蕉",col:"a bunch of bananas",ex:"Monkeys love bananas.",sy:"ba-na-na",tip:"b-a-n-a-n-a"},
  {w:"bank",ph:"/bæŋk/",p:"n.",m:"银行；河岸",col:"bank account / river bank",ex:"Dad goes to the bank.",sy:"bank",tip:"banker=银行家"},
  {w:"basket",ph:"/ˈbɑːskɪt/",p:"n.",m:"篮子",col:"a basket of fruit",ex:"Put the eggs in the basket.",sy:"bas-ket",tip:"basketball=篮球"},
  {w:"bath",ph:"/bɑːθ/",p:"n.",m:"洗澡",col:"take a bath / have a bath",ex:"I take a bath every evening.",sy:"bath",tip:"bathroom=浴室"},
  {w:"be",ph:"/biː/",p:"v.",m:"是；成为",col:"be happy / be quiet",ex:"I want to be a doctor.",pt:"was/were",sy:"be",tip:"am/is/are是其变形"},
  {w:"beach",ph:"/biːtʃ/",p:"n.",m:"海滩",col:"at the beach / go to the beach",ex:"We play on the beach.",sy:"beach",tip:"beach=海滩（沙子）"},
  {w:"bear",ph:"/beə/",p:"n.",m:"熊",col:"teddy bear / polar bear",ex:"The bear is big and brown.",sy:"bear",tip:"teddy bear=玩具熊"},
  {w:"beautiful",ph:"/ˈbjuːtɪfl/",p:"adj.",m:"美丽的",col:"beautiful flower / beautiful day",ex:"The flower is beautiful.",sy:"beau-ti-ful",tip:"beauty+ful=美丽"},
  {w:"because",ph:"/bɪˈkɒz/",p:"conj.",m:"因为",col:"because of",ex:"I'm happy because I got a gift.",sy:"be-cause",tip:"because+句子；because of+名词"},
  {w:"become",ph:"/bɪˈkʌm/",p:"v.",m:"成为",col:"become a teacher / become cold",ex:"She became a nurse.",pt:"became",sy:"be-come",tip:"come=来，变成"},
  {w:"bed",ph:"/bed/",p:"n.",m:"床",col:"go to bed / in bed",ex:"Time to go to bed.",sy:"bed",tip:"bedroom=卧室"},
  {w:"bedroom",ph:"/ˈbedruːm/",p:"n.",m:"卧室",col:"my bedroom / clean the bedroom",ex:"My bedroom is pink.",sy:"bed-room",tip:"bed+room=卧室"},
  {w:"before",ph:"/bɪˈfɔː/",p:"prep./conj.",m:"在…之前",col:"before class / before you go",ex:"Wash your hands before eating.",sy:"be-fore",tip:"反义词：after"},
  {w:"begin",ph:"/bɪˈɡɪn/",p:"v.",m:"开始",col:"begin to do / begin class",ex:"School begins at 8 o'clock.",pt:"began",sy:"be-gin",tip:"反义词：end/finish"},
  {w:"behind",ph:"/bɪˈhaɪnd/",p:"prep.",m:"在…后面",col:"behind the door / behind you",ex:"The cat is behind the tree.",sy:"be-hind",tip:"反义词：in front of"},
  {w:"believe",ph:"/bɪˈliːv/",p:"v.",m:"相信",col:"believe in / believe me",ex:"I believe you.",pt:"believed",sy:"be-lieve",tip:"lie=说谎，believe=相信"},
  {w:"belong",ph:"/bɪˈlɒŋ/",p:"v.",m:"属于",col:"belong to",ex:"This book belongs to me.",pt:"belonged",sy:"be-long",tip:"long=长的，属于"},
  {w:"below",ph:"/bɪˈləʊ/",p:"prep.",m:"在…下面",col:"below zero / below the table",ex:"The fish are below the surface.",sy:"be-low",tip:"反义词：above"},
  {w:"best",ph:"/best/",p:"adj./adv.",m:"最好的",col:"best friend / do one's best",ex:"She is my best friend.",sy:"best",tip:"good的最高级"},
  {w:"better",ph:"/ˈbetə/",p:"adj./adv.",m:"更好的",col:"better than / feel better",ex:"I'm better at math now.",sy:"bet-ter",tip:"good的比较级"},
  {w:"between",ph:"/bɪˈtwiːn/",p:"prep.",m:"在…之间",col:"between you and me",ex:"The park is between the school and my home.",sy:"be-tween",tip:"between用于两者之间"},
  {w:"big",ph:"/bɪɡ/",p:"adj.",m:"大的",col:"big house / big sister",ex:"The elephant is big.",sy:"big",tip:"反义词：small/little"},
  {w:"bike",ph:"/baɪk/",p:"n.",m:"自行车",col:"ride a bike / by bike",ex:"I go to school by bike.",sy:"bike",tip:"bicycle的简称"},
  {w:"bird",ph:"/bɜːd/",p:"n.",m:"鸟",col:"bird song / little bird",ex:"The bird can fly.",sy:"bird",tip:"b-i-r-d"},
  {w:"birthday",ph:"/ˈbɜːθdeɪ/",p:"n.",m:"生日",col:"happy birthday / birthday party",ex:"Happy birthday to you!",sy:"birth-day",tip:"birth=出生，day=日子"},
  {w:"biscuit",ph:"/ˈbɪskɪt/",p:"n.",m:"饼干",col:"chocolate biscuit",ex:"Would you like a biscuit?",sy:"bis-cuit",tip:"cookie=饼干（美式）"},
  {w:"bit",ph:"/bɪt/",p:"n.",m:"一点；少量",col:"a bit of / a little bit",ex:"I'm a bit tired.",sy:"bit",tip:"a bit = a little"},
  {w:"black",ph:"/blæk/",p:"adj./n.",m:"黑色的；黑色",col:"black cat / black and white",ex:"The cat is black.",sy:"black",tip:"blackboard=黑板"},
  {w:"blue",ph:"/bluː/",p:"adj./n.",m:"蓝色的；蓝色",col:"blue sky / dark blue",ex:"The sky is blue.",sy:"blue",tip:"b-l-u-e"},
  {w:"boat",ph:"/bəʊt/",p:"n.",m:"船",col:"by boat / row a boat",ex:"We went there by boat.",sy:"boat",tip:"boat<ship(大船)"},
  {w:"body",ph:"/ˈbɒdi/",p:"n.",m:"身体",col:"body parts / body language",ex:"Exercise is good for your body.",sy:"bo-dy",tip:"somebody=某人"},
  {w:"book",ph:"/bʊk/",p:"n.",m:"书",col:"read a book / book shop",ex:"I love reading story books.",sy:"book",tip:"notebook=笔记本"},
  {w:"both",ph:"/bəʊθ/",p:"pron./adj.",m:"两者都",col:"both of us / both sides",ex:"Both of my parents are teachers.",sy:"both",tip:"both指两者都"},
  {w:"bottle",ph:"/ˈbɒtl/",p:"n.",m:"瓶子",col:"a bottle of water",ex:"Please pass me the bottle.",sy:"bot-tle",tip:"water bottle=水瓶"},
  {w:"box",ph:"/bɒks/",p:"n.",m:"盒子",col:"a box of / pencil box",ex:"There is a gift in the box.",sy:"box",tip:"boxing=拳击"},
  {w:"boy",ph:"/bɔɪ/",p:"n.",m:"男孩",col:"little boy / school boy",ex:"The boy is playing football.",sy:"boy",tip:"反义词：girl"},
  {w:"bread",ph:"/bred/",p:"n.",m:"面包",col:"a piece of bread / brown bread",ex:"I had bread for breakfast.",sy:"bread",tip:"b+r+ead=面包"},
  {w:"breakfast",ph:"/ˈbrekfəst/",p:"n.",m:"早餐",col:"have breakfast / at breakfast",ex:"I eat eggs for breakfast.",sy:"break-fast",tip:"break+fast=早餐"},
  {w:"bridge",ph:"/brɪdʒ/",p:"n.",m:"桥",col:"cross the bridge / build a bridge",ex:"Walk across the bridge.",sy:"bridge",tip:"London Bridge=伦敦桥"},
  {w:"bright",ph:"/braɪt/",p:"adj.",m:"明亮的；聪明的",col:"bright light / bright girl",ex:"The sun is very bright.",sy:"bright",tip:"bright=光线好/聪明"},
  {w:"bring",ph:"/brɪŋ/",p:"v.",m:"带来",col:"bring me / bring your book",ex:"Please bring your homework.",pt:"brought",sy:"bring",tip:"反义词：take（带走）"},
  {w:"brother",ph:"/ˈbrʌðə/",p:"n.",m:"兄弟",col:"little brother / big brother",ex:"My brother is older than me.",sy:"broth-er",tip:"sister=姐妹"},
  {w:"brown",ph:"/braʊn/",p:"adj./n.",m:"棕色的；棕色",col:"brown eyes / brown bear",ex:"I have brown hair.",sy:"brown",tip:"b-r-o-w-n"},
  {w:"build",ph:"/bɪld/",p:"v.",m:"建造",col:"build a house / build a wall",ex:"Birds build nests in trees.",pt:"built",sy:"build",tip:"builder=建筑工人"},
  {w:"bunny",ph:"/ˈbʌni/",p:"n.",m:"兔子",col:"little bunny / Easter bunny",ex:"The bunny is so cute!",sy:"bun-ny",tip:"bunny=小兔子（可爱说法）"},
  {w:"bus",ph:"/bʌs/",p:"n.",m:"公共汽车",col:"by bus / bus stop",ex:"I take the bus to school.",sy:"bus",tip:"school bus=校车"},
  {w:"busy",ph:"/ˈbɪzi/",p:"adj.",m:"忙碌的",col:"be busy / busy street",ex:"Mom is busy cooking.",sy:"bu-sy",tip:"反义词：free"},
  {w:"but",ph:"/bʌt/",p:"conj.",m:"但是",col:"not...but / but also",ex:"I like cats but I don't like dogs.",sy:"but",tip:"表示转折"},
  {w:"butter",ph:"/ˈbʌtə/",p:"n.",m:"黄油",col:"bread and butter",ex:"Spread butter on the bread.",sy:"but-ter",tip:"butterfly=蝴蝶"},
  {w:"cake",ph:"/keɪk/",p:"n.",m:"蛋糕",col:"birthday cake / a piece of cake",ex:"Mom made a cake for my birthday.",sy:"cake",tip:"a piece of cake=小菜一碟"},
  {w:"call",ph:"/kɔːl/",p:"v./n.",m:"打电话；叫",col:"call me / give a call",ex:"I will call you tomorrow.",pt:"called",sy:"call",tip:"call=呼叫/打电话"},
  {w:"camera",ph:"/ˈkæmərə/",p:"n.",m:"照相机",col:"take a photo with camera",ex:"My dad has a new camera.",sy:"ca-me-ra",tip:"拍照用camera"},
  {w:"camp",ph:"/kæmp/",p:"n./v.",m:"露营；营地",col:"summer camp / go camping",ex:"We go camping in summer.",pt:"camped",sy:"camp",tip:"camping=露营活动"},
  {w:"can",ph:"/kæn/",p:"modal v.",m:"能；可以",col:"can do / can swim",ex:"I can ride a bike.",sy:"can",tip:"否定式：cannot/can't"},
  {w:"candle",ph:"/ˈkændl/",p:"n.",m:"蜡烛",col:"light a candle / birthday candle",ex:"Blow out the candles!",sy:"can-dle",tip:"生日蛋糕上插candle"},
  {w:"cap",ph:"/kæp/",p:"n.",m:"帽子；瓶盖",col:"baseball cap / bottle cap",ex:"Wear your cap in the sun.",sy:"cap",tip:"cap=有帽檐的帽子"},
  {w:"capital",ph:"/ˈkæpɪtl/",p:"n.",m:"首都；大写字母",col:"capital city / capital letter",ex:"London is the capital of the UK.",sy:"ca-pi-tal",tip:"大写字母=capital letter"},
  {w:"car",ph:"/kɑː/",p:"n.",m:"汽车",col:"by car / drive a car",ex:"We go to the park by car.",sy:"car",tip:"car=小汽车"},
  {w:"card",ph:"/kɑːd/",p:"n.",m:"卡片",col:"credit card / birthday card",ex:"I made a card for Mom.",sy:"card",tip:"postcard=明信片"},
  {w:"careful",ph:"/ˈkeəfl/",p:"adj.",m:"小心的",col:"be careful / careful with",ex:"Be careful when you cross the road.",sy:"care-ful",tip:"care+ful=充满关心=小心"},
  {w:"carry",ph:"/ˈkæri/",p:"v.",m:"携带；搬运",col:"carry a bag / carry books",ex:"Let me carry the box for you.",pt:"carried",sy:"car-ry",tip:"carry=搬运"},
  {w:"cartoon",ph:"/kɑːˈtuːn/",p:"n.",m:"卡通片",col:"watch cartoons / cartoon character",ex:"I love watching cartoons.",sy:"car-toon",tip:"cartoon=动画片"},
  {w:"cat",ph:"/kæt/",p:"n.",m:"猫",col:"black cat / cat food",ex:"The cat is drinking milk.",sy:"cat",tip:"c-a-t"},
  {w:"catch",ph:"/kætʃ/",p:"v.",m:"接住；抓住",col:"catch a ball / catch a bus",ex:"Catch the ball!",pt:"caught",sy:"catch",tip:"反义词：throw"},
  {w:"caterpillar",ph:"/ˈkætəpɪlə/",p:"n.",m:"毛毛虫",col:"caterpillar to butterfly",ex:"The caterpillar turned into a butterfly.",sy:"ca-ter-pil-lar",tip:"毛毛虫变蝴蝶"},
  {w:"chair",ph:"/tʃeə/",p:"n.",m:"椅子",col:"sit on a chair / desk and chair",ex:"Sit on your chair, please.",sy:"chair",tip:"armchair=扶手椅"},
  {w:"chance",ph:"/tʃɑːns/",p:"n.",m:"机会",col:"have a chance / take a chance",ex:"I have a chance to win.",sy:"chance",tip:"by chance=偶然"},
  {w:"change",ph:"/tʃeɪndʒ/",p:"v./n.",m:"改变；零钱",col:"change your mind / change clothes",ex:"Let's change the plan.",pt:"changed",sy:"change",tip:"change=改变/零钱"},
  {w:"cheap",ph:"/tʃiːp/",p:"adj.",m:"便宜的",col:"cheap and nice / cheap price",ex:"This toy is cheap.",sy:"cheap",tip:"反义词：expensive"},
  {w:"cheese",ph:"/tʃiːz/",p:"n.",m:"奶酪",col:"cheese sandwich / a slice of cheese",ex:"Mice love cheese.",sy:"cheese",tip:"cheese=芝士"},
  {w:"chicken",ph:"/ˈtʃɪkɪn/",p:"n.",m:"鸡；鸡肉",col:"chicken soup / fried chicken",ex:"I like eating chicken.",sy:"chick-en",tip:"chick=小鸡"},
  {w:"child",ph:"/tʃaɪld/",p:"n.",m:"孩子",col:"only child / children's day",ex:"The child is playing.",sy:"child",tip:"复数：children"},
  {w:"chocolate",ph:"/ˈtʃɒklət/",p:"n.",m:"巧克力",col:"chocolate cake / hot chocolate",ex:"I love chocolate ice cream.",sy:"choc-o-late",tip:"choco+late"},
  {w:"choose",ph:"/tʃuːz/",p:"v.",m:"选择",col:"choose a book / choose from",ex:"Which one do you choose?",pt:"chose",sy:"choose",tip:"choose=挑选"},
  {w:"Christmas",ph:"/ˈkrɪsməs/",p:"n.",m:"圣诞节",col:"Merry Christmas / Christmas tree",ex:"We decorate the Christmas tree.",sy:"Christ-mas",tip:"Xmas=Christmas缩写"},
  {w:"city",ph:"/ˈsɪti/",p:"n.",m:"城市",col:"big city / city centre",ex:"London is a big city.",sy:"ci-ty",tip:"反义词：countryside"},
  {w:"class",ph:"/klɑːs/",p:"n.",m:"班级；课",col:"in class / after class",ex:"We have English class today.",sy:"class",tip:"classroom=教室"},
  {w:"clean",ph:"/kliːn/",p:"v./adj.",m:"打扫；干净的",col:"clean the room / clean water",ex:"Please clean your room.",pt:"cleaned",sy:"clean",tip:"反义词：dirty"},
  {w:"clever",ph:"/ˈklevə/",p:"adj.",m:"聪明的",col:"clever boy / clever idea",ex:"What a clever idea!",sy:"clev-er",tip:"同义词：smart/bright"},
  {w:"climb",ph:"/klaɪm/",p:"v.",m:"爬",col:"climb a tree / climb a mountain",ex:"The cat climbed the tree.",pt:"climbed",sy:"climb",tip:"b不发音"},
  {w:"clock",ph:"/klɒk/",p:"n.",m:"钟",col:"alarm clock / o'clock",ex:"The clock says 3 o'clock.",sy:"clock",tip:"o'clock=of the clock"},
  {w:"close",ph:"/kləʊz/",p:"v.",m:"关闭",col:"close the door / close your eyes",ex:"Please close the window.",pt:"closed",sy:"close",tip:"反义词：open"},
  {w:"clothes",ph:"/kləʊðz/",p:"n.",m:"衣服",col:"put on clothes / warm clothes",ex:"I need new clothes.",sy:"clothes",tip:"cloth=布料"},
  {w:"cloud",ph:"/klaʊd/",p:"n.",m:"云",col:"white cloud / in the clouds",ex:"The clouds are white.",sy:"cloud",tip:"cloudy=多云的"},
  {w:"coat",ph:"/kəʊt/",p:"n.",m:"外套",col:"winter coat / put on a coat",ex:"Wear your coat. It's cold.",sy:"coat",tip:"raincoat=雨衣"},
  {w:"coffee",ph:"/ˈkɒfi/",p:"n.",m:"咖啡",col:"a cup of coffee / drink coffee",ex:"Dad drinks coffee every morning.",sy:"cof-fee",tip:"c-o-f-f-e-e"},
  {w:"cold",ph:"/kəʊld/",p:"adj./n.",m:"冷的；感冒",col:"cold water / catch a cold",ex:"It's cold outside.",sy:"cold",tip:"反义词：hot"},
  {w:"colour",ph:"/ˈkʌlə/",p:"n.",m:"颜色",col:"what colour / bright colours",ex:"What colour is your bag?",sy:"col-our",tip:"美式拼写：color"},
  {w:"come",ph:"/kʌm/",p:"v.",m:"来",col:"come in / come here / come home",ex:"Come here, please.",pt:"came",sy:"come",tip:"反义词：go"},
  {w:"comfortable",ph:"/ˈkʌmftəbl/",p:"adj.",m:"舒适的",col:"comfortable chair / feel comfortable",ex:"The sofa is comfortable.",sy:"com-fort-a-ble",tip:"comfort+able=舒适的"},
  {w:"computer",ph:"/kəmˈpjuːtə/",p:"n.",m:"电脑",col:"use a computer / computer game",ex:"I play games on the computer.",sy:"com-pu-ter",tip:"computer=电脑"},
  {w:"cook",ph:"/kʊk/",p:"v.",m:"做饭",col:"cook dinner / love cooking",ex:"Mom is cooking dinner.",pt:"cooked",sy:"cook",tip:"cooker=厨具"},
  {w:"cool",ph:"/kuːl/",p:"adj.",m:"酷的；凉的",col:"cool water / cool guy",ex:"That's a cool bike!",sy:"cool",tip:"cool=凉快/很酷"},
  {w:"count",ph:"/kaʊnt/",p:"v.",m:"数数",col:"count to ten / count numbers",ex:"Let's count from 1 to 10.",pt:"counted",sy:"count",tip:"counter=计数器"},
  {w:"country",ph:"/ˈkʌntri/",p:"n.",m:"国家；乡村",col:"different countries / in the country",ex:"China is a big country.",sy:"coun-try",tip:"countryside=乡村"},
  {w:"cousin",ph:"/ˈkʌzn/",p:"n.",m:"表兄弟姐妹",col:"my cousin / cousin brother",ex:"My cousin lives in Shanghai.",sy:"cou-sin",tip:"堂/表兄弟姐妹"},
  {w:"cover",ph:"/ˈkʌvə/",p:"v./n.",m:"覆盖；封面",col:"cover the book / book cover",ex:"Cover your mouth when you cough.",pt:"covered",sy:"cov-er",tip:"discover=发现"},
  {w:"cow",ph:"/kaʊ/",p:"n.",m:"奶牛",col:"milk the cow / cow farm",ex:"The cow gives us milk.",sy:"cow",tip:"cowboy=牛仔"},
  {w:"crayon",ph:"/ˈkreɪɒn/",p:"n.",m:"蜡笔",col:"colour with crayons / crayon box",ex:"I draw with crayons.",sy:"cray-on",tip:"crayon=蜡笔"},
  {w:"crazy",ph:"/ˈkreɪzi/",p:"adj.",m:"疯狂的",col:"go crazy / crazy about",ex:"I'm crazy about football.",sy:"cra-zy",tip:"crazy=疯狂/着迷"},
  {w:"cream",ph:"/kriːm/",p:"n.",m:"奶油",col:"ice cream / whipped cream",ex:"I want an ice cream.",sy:"cream",tip:"ice cream=冰淇淋"},
  {w:"crocodile",ph:"/ˈkrɒkədaɪl/",p:"n.",m:"鳄鱼",col:"crocodile tears",ex:"The crocodile has big teeth.",sy:"cro-co-dile",tip:"crocodile tears=假慈悲"},
  {w:"cross",ph:"/krɒs/",p:"v./n.",m:"穿过；十字",col:"cross the road / cross out",ex:"Look both ways before you cross.",pt:"crossed",sy:"cross",tip:"zebra crossing=斑马线"},
  {w:"cry",ph:"/kraɪ/",p:"v.",m:"哭；喊",col:"cry for help / start crying",ex:"Don't cry. It's okay.",pt:"cried",sy:"cry",tip:"反义词：laugh"},
  {w:"cup",ph:"/kʌp/",p:"n.",m:"杯子",col:"a cup of tea / cup of water",ex:"I drink a cup of milk.",sy:"cup",tip:"cup=杯子（带把）"},
  {w:"cute",ph:"/kjuːt/",p:"adj.",m:"可爱的",col:"cute baby / cute dog",ex:"The puppy is so cute!",sy:"cute",tip:"c-u-t-e"},
  {w:"cut",ph:"/kʌt/",p:"v.",m:"切；剪",col:"cut paper / cut the cake",ex:"Cut the paper with scissors.",pt:"cut",sy:"cut",tip:"cut=切割"},
  {w:"dance",ph:"/dɑːns/",p:"v./n.",m:"跳舞",col:"dance to music / dance class",ex:"She loves to dance.",pt:"danced",sy:"dance",tip:"dancer=舞者"},
  {w:"dangerous",ph:"/ˈdeɪndʒərəs/",p:"adj.",m:"危险的",col:"dangerous animal / be dangerous",ex:"It's dangerous to run in the street.",sy:"dan-ger-ous",tip:"danger+ous=充满危险的"},
  {w:"dark",ph:"/dɑːk/",p:"adj.",m:"黑暗的；深色的",col:"dark room / dark blue",ex:"It's dark outside.",sy:"dark",tip:"反义词：light"},
  {w:"date",ph:"/deɪt/",p:"n.",m:"日期；约会",col:"what date / date of birth",ex:"What's the date today?",sy:"date",tip:"today's date=今天的日期"},
  {w:"daughter",ph:"/ˈdɔːtə/",p:"n.",m:"女儿",col:"my daughter / little daughter",ex:"My daughter is 7 years old.",sy:"daugh-ter",tip:"反义词：son"},
  {w:"day",ph:"/deɪ/",p:"n.",m:"天；日子",col:"every day / all day / sunny day",ex:"It's a beautiful day.",sy:"day",tip:"birthday=生日"},
  {w:"dear",ph:"/dɪə/",p:"adj.",m:"亲爱的；贵的",col:"Dear Mom / dear me",ex:"Dear Santa, I want a bike.",sy:"dear",tip:"deer=鹿（同音）"},
  {w:"December",ph:"/dɪˈsembə/",p:"n.",m:"十二月",col:"in December / December 25th",ex:"Christmas is in December.",sy:"De-cem-ber",tip:"Dec是缩写"},
  {w:"decide",ph:"/dɪˈsaɪd/",p:"v.",m:"决定",col:"decide to do / decide on",ex:"I decided to learn to swim.",pt:"decided",sy:"de-cide",tip:"decision=决定（名词）"},
  {w:"deep",ph:"/diːp/",p:"adj.",m:"深的",col:"deep water / deep sea",ex:"The water is very deep.",sy:"deep",tip:"反义词：shallow"},
  {w:"delicious",ph:"/dɪˈlɪʃəs/",p:"adj.",m:"美味的",col:"delicious food / taste delicious",ex:"The cake is delicious!",sy:"de-li-cious",tip:"yummy=好吃（口语）"},
  {w:"dentist",ph:"/ˈdentɪst/",p:"n.",m:"牙医",col:"go to the dentist",ex:"I need to see the dentist.",sy:"den-tist",tip:"den(t)=牙齿"},
  {w:"describe",ph:"/dɪˈskraɪb/",p:"v.",m:"描述",col:"describe the picture",ex:"Can you describe your pet?",pt:"described",sy:"de-scribe",tip:"scription=写"},
  {w:"desk",ph:"/desk/",p:"n.",m:"书桌",col:"sit at the desk / on the desk",ex:"My desk is tidy.",sy:"desk",tip:"desk=学习桌"},
  {w:"dictionary",ph:"/ˈdɪkʃənri/",p:"n.",m:"词典",col:"look it up in a dictionary",ex:"Use a dictionary to find new words.",sy:"dic-tion-a-ry",tip:"dict=说，ion+ary"},
  {w:"different",ph:"/ˈdɪfrənt/",p:"adj.",m:"不同的",col:"different colours / be different from",ex:"We are in different classes.",sy:"dif-fe-rent",tip:"反义词：same"},
  {w:"difficult",ph:"/ˈdɪfɪkəlt/",p:"adj.",m:"困难的",col:"difficult question / too difficult",ex:"The test was difficult.",sy:"dif-fi-cult",tip:"反义词：easy"},
  {w:"dig",ph:"/dɪɡ/",p:"v.",m:"挖",col:"dig a hole / dig in the sand",ex:"The dog is digging a hole.",pt:"dug",sy:"dig",tip:"dig→dug→dug"},
  {w:"dinner",ph:"/ˈdɪnə/",p:"n.",m:"晚餐",col:"have dinner / dinner time",ex:"We have dinner at 6 o'clock.",sy:"din-ner",tip:"supper=晚餐（口语）"},
  {w:"dinosaur",ph:"/ˈdaɪnəsɔː/",p:"n.",m:"恐龙",col:"dinosaur toy / dinosaur bones",ex:"The dinosaur is very big.",sy:"di-no-saur",tip:"dino+saur"},
  {w:"dirty",ph:"/ˈdɜːti/",p:"adj.",m:"脏的",col:"dirty hands / dirty clothes",ex:"My hands are dirty.",sy:"dir-ty",tip:"反义词：clean"},
  {w:"discover",ph:"/dɪˈskʌvə/",p:"v.",m:"发现",col:"discover a new place",ex:"Columbus discovered America.",pt:"discovered",sy:"dis-cov-er",tip:"dis+cover=揭开"},
  {w:"dish",ph:"/dɪʃ/",p:"n.",m:"碟子；菜肴",col:"wash dishes / favourite dish",ex:"I'll wash the dishes.",sy:"dish",tip:"dish=盘子/菜"},
  {w:"do",ph:"/duː/",p:"v.",m:"做",col:"do homework / do housework",ex:"I do my homework every day.",pt:"did",sy:"do",tip:"does/did/done变形"},
  {w:"doctor",ph:"/ˈdɒktə/",p:"n.",m:"医生",col:"see a doctor / doctor's office",ex:"I want to be a doctor.",sy:"doc-tor",tip:"Dr.是缩写"},
  {w:"dog",ph:"/dɒɡ/",p:"n.",m:"狗",col:"pet dog / walk the dog",ex:"The dog is my best friend.",sy:"dog",tip:"d-o-g"},
  {w:"doll",ph:"/dɒl/",p:"n.",m:"洋娃娃",col:"play with dolls / doll house",ex:"She loves her doll.",sy:"doll",tip:"doll=娃娃"},
  {w:"dolphin",ph:"/ˈdɒlfɪn/",p:"n.",m:"海豚",col:"dolphin show / swim like a dolphin",ex:"Dolphins are very smart.",sy:"dol-phin",tip:"dolphin=海豚"},
  {w:"door",ph:"/dɔː/",p:"n.",m:"门",col:"open the door / next door",ex:"Please open the door.",sy:"door",tip:"outdoor=户外的"},
  {w:"down",ph:"/daʊn/",p:"adv./prep.",m:"向下",col:"sit down / go down / up and down",ex:"Sit down, please.",pt:"downed",sy:"down",tip:"反义词：up"},
  {w:"draw",ph:"/drɔː/",p:"v.",m:"画画",col:"draw a picture / draw a line",ex:"I like to draw animals.",pt:"drew",sy:"draw",tip:"drawing=画画"},
  {w:"dream",ph:"/driːm/",p:"n./v.",m:"梦想；做梦",col:"have a dream / dream about",ex:"I had a strange dream.",pt:"dreamed/dreamt",sy:"dream",tip:"daydream=白日梦"},
  {w:"dress",ph:"/dres/",p:"n./v.",m:"连衣裙；穿衣服",col:"wear a dress / get dressed",ex:"She is wearing a red dress.",pt:"dressed",sy:"dress",tip:"dress up=打扮"},
  {w:"drink",ph:"/drɪŋk/",p:"v./n.",m:"喝；饮料",col:"drink water / a cold drink",ex:"Drink some water, please.",pt:"drank",sy:"drink",tip:"drink→drank→drunk"},
  {w:"drive",ph:"/draɪv/",p:"v.",m:"驾驶",col:"drive a car / drive to work",ex:"Dad drives me to school.",pt:"drove",sy:"drive",tip:"driver=司机"},
  {w:"drop",ph:"/drɒp/",p:"v./n.",m:"掉落；滴",col:"drop the ball / a drop of water",ex:"Don't drop the glass!",pt:"droped",sy:"drop",tip:"raindrop=雨滴"},
  {w:"duck",ph:"/dʌk/",p:"n.",m:"鸭子",col:"duck pond / baby duck",ex:"The duck is swimming.",sy:"duck",tip:"d-u-c-k"},
  {w:"dumpling",ph:"/ˈdʌmplɪŋ/",p:"n.",m:"饺子",col:"make dumplings / eat dumplings",ex:"We eat dumplings at Chinese New Year.",sy:"dump-ling",tip:"dumpling=饺子"},
  {w:"during",ph:"/ˈdjʊərɪŋ/",p:"prep.",m:"在…期间",col:"during class / during the summer",ex:"Don't talk during the lesson.",sy:"du-ring",tip:"during=在…期间"},
  {w:"duty",ph:"/ˈdjuːti/",p:"n.",m:"职责；值日",col:"on duty / do one's duty",ex:"Who's on duty today?",sy:"du-ty",tip:"on duty=值日"},
  {w:"each",ph:"/iːtʃ/",p:"pron./adj.",m:"每个",col:"each other / each of us",ex:"Each student has a book.",sy:"each",tip:"each other=互相"},
  {w:"ear",ph:"/ɪə/",p:"n.",m:"耳朵",col:"ear ache / big ears",ex:"The rabbit has long ears.",sy:"ear",tip:"hear=听见（用耳）"},
  {w:"early",ph:"/ˈɜːli/",p:"adj./adv.",m:"早的",col:"early in the morning / get up early",ex:"I get up early every day.",sy:"ear-ly",tip:"反义词：late"},
  {w:"earth",ph:"/ɜːθ/",p:"n.",m:"地球；泥土",col:"on Earth / the earth",ex:"The Earth goes around the Sun.",sy:"earth",tip:"on Earth=在地球上"},
  {w:"east",ph:"/iːst/",p:"n./adj.",m:"东方",col:"east of / East China",ex:"The sun rises in the east.",sy:"east",tip:"反义词：west"},
  {w:"Easter",ph:"/ˈiːstə/",p:"n.",m:"复活节",col:"Easter egg / Happy Easter",ex:"We paint Easter eggs.",sy:"Eas-ter",tip:"复活节彩蛋"},
  {w:"easy",ph:"/ˈiːzi/",p:"adj.",m:"容易的",col:"easy question / take it easy",ex:"This test is easy.",sy:"ea-sy",tip:"反义词：difficult"},
  {w:"eat",ph:"/iːt/",p:"v.",m:"吃",col:"eat breakfast / eat out",ex:"I eat an apple every day.",pt:"ate",sy:"eat",tip:"eat→ate→eaten"},
  {w:"egg",ph:"/eɡ/",p:"n.",m:"蛋",col:"boiled egg / egg white",ex:"I had an egg for breakfast.",sy:"egg",tip:"e-g-g"},
  {w:"eight",ph:"/eɪt/",p:"num.",m:"八",col:"eight books / eight years old",ex:"I am eight years old.",sy:"eight",tip:"8个字母：e-i-g-h-t"},
  {w:"either",ph:"/ˈaɪðə/",p:"adv./pron.",m:"（两者中）任何一个",col:"either...or / me either",ex:"Either answer is correct.",pt:"eithered",sy:"ei-ther",tip:"either...or 要么…要么"},
  {w:"elephant",ph:"/ˈelɪfənt/",p:"n.",m:"大象",col:"elephant trunk / baby elephant",ex:"The elephant is very big.",sy:"el-e-phant",tip:"e-l-e-p-h-a-n-t"},
  {w:"else",ph:"/els/",p:"adv.",m:"其他；别的",col:"something else / or else",ex:"What else do you want?",sy:"else",tip:"else放在疑问词后面"},
  {w:"empty",ph:"/ˈempti/",p:"adj.",m:"空的",col:"empty bottle / empty box",ex:"The box is empty.",sy:"emp-ty",tip:"反义词：full"},
  {w:"end",ph:"/end/",p:"n./v.",m:"结束；末尾",col:"in the end / at the end of",ex:"The story has a happy end.",pt:"ended",sy:"end",tip:"反义词：begin/start"},
  {w:"energy",ph:"/ˈenədʒi/",p:"n.",m:"能量；精力",col:"full of energy / save energy",ex:"Children have lots of energy.",sy:"en-er-gy",tip:"energetic=精力充沛的"},
  {w:"engineer",ph:"/ˌendʒɪˈnɪə/",p:"n.",m:"工程师",col:"software engineer / train engineer",ex:"My uncle is an engineer.",sy:"en-gi-neer",tip:"engine+er=工程师"},
  {w:"enjoy",ph:"/ɪnˈdʒɔɪ/",p:"v.",m:"享受；喜欢",col:"enjoy doing / enjoy the party",ex:"I enjoy reading books.",pt:"enjoyed",sy:"en-joy",tip:"joy=快乐"},
  {w:"enough",ph:"/ɪˈnʌf/",p:"adj./adv.",m:"足够的",col:"big enough / enough time",ex:"We have enough food.",sy:"e-nough",tip:"enough放形容词后面"},
  {w:"enter",ph:"/ˈentə/",p:"v.",m:"进入",col:"enter the room / enter a competition",ex:"Please enter the classroom quietly.",pt:"entered",sy:"en-ter",tip:"反义词：exit"},
  {w:"envelope",ph:"/ˈenvələʊp/",p:"n.",m:"信封",col:"post an envelope / open an envelope",ex:"Put the letter in the envelope.",sy:"en-ve-lope",tip:"vel=包，信封"},
  {w:"eraser",ph:"/ɪˈreɪzə/",p:"n.",m:"橡皮",col:"eraser / pencil and eraser",ex:"I use an eraser to correct mistakes.",sy:"e-ra-ser",tip:"erase=擦掉"},
  {w:"especially",ph:"/ɪˈspeʃəli/",p:"adv.",m:"特别；尤其",col:"especially today",ex:"I like fruit, especially apples.",sy:"es-pe-cial-ly",tip:"especial+ly=尤其"},
  {w:"evening",ph:"/ˈiːvnɪŋ/",p:"n.",m:"傍晚；晚上",col:"in the evening / good evening",ex:"We watch TV in the evening.",sy:"eve-ning",tip:"eve=前夕"},
  {w:"event",ph:"/ɪˈvent/",p:"n.",m:"事件；活动",col:"special event / school event",ex:"The sports day is a big event.",sy:"e-vent",tip:"e+vent=出来"},
  {w:"ever",ph:"/ˈevə/",p:"adv.",m:"曾经",col:"ever been / for ever",ex:"Have you ever been to London?",sy:"ev-er",tip:"for ever=永远"},
  {w:"every",ph:"/ˈevri/",p:"adj.",m:"每个的",col:"every day / every week",ex:"I go to school every day.",sy:"eve-ry",tip:"everyone=每个人"},
  {w:"example",ph:"/ɪɡˈzɑːmpl/",p:"n.",m:"例子",col:"for example / give an example",ex:"For example, a dog is an animal.",sy:"ex-am-ple",tip:"for example=例如"},
  {w:"excellent",ph:"/ˈeksələnt/",p:"adj.",m:"优秀的",col:"excellent job / excellent work",ex:"Your work is excellent!",sy:"ex-cel-lent",tip:"excel=超越"},
  {w:"excited",ph:"/ɪkˈsaɪtɪd/",p:"adj.",m:"兴奋的",col:"excited about / get excited",ex:"I'm excited about the trip.",sy:"ex-ci-ted",tip:"excite=使兴奋"},
  {w:"excuse",ph:"/ɪkˈskjuːz/",p:"v./n.",m:"原谅；借口",col:"excuse me / make an excuse",ex:"Excuse me, where's the toilet?",pt:"excused",sy:"ex-cuse",tip:"excuse me=对不起/打扰了"},
  {w:"exercise",ph:"/ˈeksəsaɪz/",p:"n./v.",m:"锻炼；练习",col:"do exercise / exercise book",ex:"We do morning exercise every day.",pt:"exercised",sy:"ex-er-cise",tip:"exercise=运动/练习"},
  {w:"expect",ph:"/ɪkˈspekt/",p:"v.",m:"期待",col:"expect to do / expect sb",ex:"I expect you to be on time.",pt:"expected",sy:"ex-pect",tip:"ex+pect=向外看=期待"},
  {w:"expensive",ph:"/ɪkˈspensɪv/",p:"adj.",m:"昂贵的",col:"expensive gift / too expensive",ex:"The phone is too expensive.",sy:"ex-pen-sive",tip:"反义词：cheap"},
  {w:"experience",ph:"/ɪkˈspɪəriəns/",p:"n.",m:"经验；经历",col:"work experience / have experience",ex:"I had a wonderful experience.",sy:"ex-pe-ri-ence",tip:"ex+peri+ence"},
  {w:"experiment",ph:"/ɪkˈsperɪmənt/",p:"n.",m:"实验",col:"do an experiment / science experiment",ex:"We did a fun experiment in class.",sy:"ex-per-i-ment",tip:"ex+peri+ment"},
  {w:"explain",ph:"/ɪkˈspleɪn/",p:"v.",m:"解释",col:"explain to / explain why",ex:"Can you explain this word?",pt:"explained",sy:"ex-plain",tip:"plain=清楚的"},
  {w:"explore",ph:"/ɪkˈsplɔː/",p:"v.",m:"探索",col:"explore the world / explore the cave",ex:"Let's explore the forest!",pt:"explored",sy:"ex-plore",tip:"explorer=探险家"},
  {w:"extra",ph:"/ˈekstrə/",p:"adj.",m:"额外的",col:"extra time / extra money",ex:"I need some extra help.",sy:"ex-tra",tip:"extra=额外的"},
  {w:"eye",ph:"/aɪ/",p:"n.",m:"眼睛",col:"blue eyes / close your eyes",ex:"Close your eyes and sleep.",sy:"eye",tip:"e-y-e"},
  {w:"face",ph:"/feɪs/",p:"n.",m:"脸",col:"wash your face / happy face",ex:"She has a round face.",sy:"face",tip:"facial=面部的"},
  {w:"factory",ph:"/ˈfæktri/",p:"n.",m:"工厂",col:"car factory / work in a factory",ex:"My dad works in a factory.",sy:"fac-to-ry",tip:"fact=制造"},
  {w:"family",ph:"/ˈfæməli/",p:"n.",m:"家庭",col:"family members / family photo",ex:"I love my family.",sy:"fa-mi-ly",tip:"fa-mi-ly"},
  {w:"fantastic",ph:"/fænˈtæstɪk/",p:"adj.",m:"极好的",col:"fantastic idea / fantastic job",ex:"That's a fantastic idea!",sy:"fan-tas-tic",tip:"fantasy=幻想"},
  {w:"farm",ph:"/fɑːm/",p:"n.",m:"农场",col:"on the farm / farm animals",ex:"Grandpa lives on a farm.",sy:"farm",tip:"farmer=农民"},
  {w:"fast",ph:"/fɑːst/",p:"adj./adv.",m:"快的；快速地",col:"fast food / run fast",ex:"The rabbit is very fast.",sy:"fast",tip:"反义词：slow"},
  {w:"fat",ph:"/fæt/",p:"adj.",m:"胖的",col:"fat cat / get fat",ex:"My cat is fat.",sy:"fat",tip:"反义词：thin"},
  {w:"father",ph:"/ˈfɑːðə/",p:"n.",m:"父亲",col:"my father / Father's Day",ex:"My father is a doctor.",sy:"fa-ther",tip:"dad=爸爸（口语）"},
  {w:"favourite",ph:"/ˈfeɪvərɪt/",p:"adj./n.",m:"最喜欢的",col:"favourite food / my favourite",ex:"My favourite colour is blue.",sy:"fa-vou-rite",tip:"美式：favorite"},
  {w:"February",ph:"/ˈfebruəri/",p:"n.",m:"二月",col:"in February / February 14th",ex:"February is the shortest month.",sy:"Feb-ru-a-ry",tip:"Feb是缩写"},
  {w:"feel",ph:"/fiːl/",p:"v.",m:"感觉",col:"feel happy / feel tired",ex:"I feel cold.",pt:"felt",sy:"feel",tip:"feeling=感觉"},
  {w:"fence",ph:"/fens/",p:"n.",m:"篱笆",col:"wooden fence / climb the fence",ex:"There is a white fence.",sy:"fence",tip:"fence=围栏"},
  {w:"festival",ph:"/ˈfestɪvl/",p:"n.",m:"节日",col:"Spring Festival / music festival",ex:"The Spring Festival is in winter.",sy:"fes-ti-val",tip:"festival=节日"},
  {w:"field",ph:"/fiːld/",p:"n.",m:"田地；运动场",col:"football field / rice field",ex:"The children play in the field.",sy:"field",tip:"field=场地/田野"},
  {w:"fill",ph:"/fɪl/",p:"v.",m:"装满",col:"fill the cup / fill in",ex:"Fill the cup with water.",pt:"filled",sy:"fill",tip:"full=满的"},
  {w:"film",ph:"/fɪlm/",p:"n.",m:"电影；胶卷",col:"watch a film / film star",ex:"Let's watch a film.",sy:"film",tip:"movie=电影（美式）"},
  {w:"find",ph:"/faɪnd/",p:"v.",m:"找到",col:"find a book / find out",ex:"I can't find my pen.",pt:"found",sy:"find",tip:"find→found→found"},
  {w:"fine",ph:"/faɪn/",p:"adj.",m:"好的；晴朗的",col:"I'm fine / fine weather",ex:"I'm fine, thank you.",sy:"fine",tip:"fine=好/罚款"},
  {w:"finger",ph:"/ˈfɪŋɡə/",p:"n.",m:"手指",col:"little finger / count on fingers",ex:"She has long fingers.",sy:"fin-ger",tip:"thumb=大拇指"},
  {w:"finish",ph:"/ˈfɪnɪʃ/",p:"v.",m:"完成",col:"finish homework / finish school",ex:"I finished my homework.",pt:"finished",sy:"fi-nish",tip:"反义词：start"},
  {w:"fire",ph:"/ˈfaɪə/",p:"n.",m:"火",col:"play with fire / on fire",ex:"Fire is very hot.",sy:"fire",tip:"firefighter=消防员"},
  {w:"first",ph:"/fɜːst/",p:"adj./adv.",m:"第一；首先",col:"first day / at first",ex:"I was first in the race.",sy:"first",tip:"反义词：last"},
  {w:"fish",ph:"/fɪʃ/",p:"n./v.",m:"鱼；钓鱼",col:"go fishing / fish and chips",ex:"I like to eat fish.",pt:"fished",sy:"fish",tip:"复数形式：fish"},
  {w:"five",ph:"/faɪv/",p:"num.",m:"五",col:"five fingers / five years old",ex:"I have five sweets.",sy:"five",tip:"f-i-v-e"},
  {w:"flag",ph:"/flæɡ/",p:"n.",m:"旗帜",col:"national flag / red flag",ex:"The flag is red and yellow.",sy:"flag",tip:"f-l-a-g"},
  {w:"flat",ph:"/flæt/",p:"adj./n.",m:"平坦的；公寓",col:"flat floor / live in a flat",ex:"We live in a flat.",sy:"flat",tip:"apartment=公寓（美式）"},
  {w:"floor",ph:"/flɔː/",p:"n.",m:"地板；楼层",col:"on the floor / first floor",ex:"Don't sit on the floor.",sy:"floor",tip:"ground floor=一楼"},
  {w:"flower",ph:"/ˈflaʊə/",p:"n.",m:"花",col:"pick flowers / flower garden",ex:"The flowers are beautiful.",sy:"flow-er",tip:"flour=面粉（同音）"},
  {w:"fly",ph:"/flaɪ/",p:"v./n.",m:"飞；苍蝇",col:"fly a kite / fly in the sky",ex:"Birds can fly.",pt:"flew",sy:"fly",tip:"butterfly=蝴蝶"},
  {w:"follow",ph:"/ˈfɒləʊ/",p:"v.",m:"跟随",col:"follow me / follow the rules",ex:"Follow me, please.",pt:"followed",sy:"fol-low",tip:"following=接下来的"},
  {w:"food",ph:"/fuːd/",p:"n.",m:"食物",col:"delicious food / fast food",ex:"I love Chinese food.",sy:"food",tip:"food=食物（不可数）"},
  {w:"foot",ph:"/fʊt/",p:"n.",m:"脚；英尺",col:"on foot / foot ball",ex:"I go to school on foot.",sy:"foot",tip:"复数：feet"},
  {w:"football",ph:"/ˈfʊtbɔːl/",p:"n.",m:"足球",col:"play football / football match",ex:"Boys are playing football.",sy:"foot-ball",tip:"foot+ball=足球"},
  {w:"for",ph:"/fɔː/",p:"prep.",m:"为了；给",col:"for you / for breakfast",ex:"This gift is for you.",sy:"for",tip:"four=四（同音）"},
  {w:"foreign",ph:"/ˈfɒrən/",p:"adj.",m:"外国的",col:"foreign language / foreign country",ex:"I want to learn a foreign language.",sy:"for-eign",tip:"g不发音"},
  {w:"forest",ph:"/ˈfɒrɪst/",p:"n.",m:"森林",col:"in the forest / forest fire",ex:"The forest is green.",sy:"for-est",tip:"forest=大森林"},
  {w:"forever",ph:"/fərˈevə/",p:"adv.",m:"永远",col:"forever friend / forever love",ex:"I will remember you forever.",sy:"for-ev-er",tip:"for+ever=永远"},
  {w:"forget",ph:"/fəˈɡet/",p:"v.",m:"忘记",col:"forget to do / forget about",ex:"Don't forget your bag!",pt:"forgot",sy:"for-get",tip:"反义词：remember"},
  {w:"fork",ph:"/fɔːk/",p:"n.",m:"叉子",col:"knife and fork / fork and spoon",ex:"Use a fork to eat noodles.",sy:"fork",tip:"f-o-r-k"},
  {w:"four",ph:"/fɔː/",p:"num.",m:"四",col:"four seasons / four cats",ex:"There are four chairs.",sy:"four",tip:"f-o-u-r"},
  {w:"fox",ph:"/fɒks/",p:"n.",m:"狐狸",col:"fox tail / clever fox",ex:"The fox is very clever.",sy:"fox",tip:"f-o-x"},
  {w:"free",ph:"/friː/",p:"adj.",m:"自由的；免费的",col:"free time / free ticket",ex:"Are you free this afternoon?",sy:"free",tip:"freedom=自由"},
  {w:"fresh",ph:"/freʃ/",p:"adj.",m:"新鲜的",col:"fresh air / fresh fruit",ex:"The air is fresh in the park.",sy:"fresh",tip:"fresh=新鲜"},
  {w:"Friday",ph:"/ˈfraɪdeɪ/",p:"n.",m:"星期五",col:"on Friday / Friday night",ex:"Friday is my favourite day.",sy:"Fri-day",tip:"Fri是缩写"},
  {w:"fridge",ph:"/frɪdʒ/",p:"n.",m:"冰箱",col:"open the fridge / in the fridge",ex:"Put the milk in the fridge.",sy:"fridge",tip:"refrigerator的简称"},
  {w:"friend",ph:"/frend/",p:"n.",m:"朋友",col:"best friend / make friends",ex:"She is my best friend.",sy:"friend",tip:"friendly=友好的"},
  {w:"frog",ph:"/frɒɡ/",p:"n.",m:"青蛙",col:"frog legs / jump like a frog",ex:"The frog is green.",sy:"frog",tip:"f-r-o-g"},
  {w:"from",ph:"/frɒm/",p:"prep.",m:"从；来自",col:"from China / from morning to night",ex:"I'm from Beijing.",sy:"from",tip:"from=来自/从..."},
  {w:"front",ph:"/frʌnt/",p:"n./adj.",m:"前面；前面的",col:"in front of / front door",ex:"There is a garden in front of the house.",sy:"front",tip:"反义词：back"},
  {w:"fruit",ph:"/fruːt/",p:"n.",m:"水果",col:"fresh fruit / fruit juice",ex:"I like to eat fruit.",sy:"fruit",tip:"fruit=水果（集合名词）"},
  {w:"full",ph:"/fʊl/",p:"adj.",m:"满的；饱的",col:"full of / I'm full",ex:"The box is full of toys.",sy:"full",tip:"反义词：empty"},
  {w:"fun",ph:"/fʌn/",p:"n./adj.",m:"乐趣；有趣的",col:"have fun / fun game",ex:"We had fun at the park.",sy:"fun",tip:"funny=好笑的"},
  {w:"future",ph:"/ˈfjuːtʃə/",p:"n.",m:"未来",col:"in the future / future plan",ex:"What do you want to be in the future?",sy:"fu-ture",tip:"past=过去"},
  {w:"game",ph:"/ɡeɪm/",p:"n.",m:"游戏；比赛",col:"play games / video game",ex:"Let's play a game.",sy:"game",tip:"game=游戏/比赛"},
  {w:"garden",ph:"/ˈɡɑːdn/",p:"n.",m:"花园",col:"in the garden / garden party",ex:"The garden has many flowers.",sy:"gar-den",tip:"gardener=园丁"},
  {w:"get",ph:"/ɡet/",p:"v.",m:"得到；拿",col:"get up / get ready / get home",ex:"I get up at 7 o'clock.",pt:"got",sy:"get",tip:"get→got→got/gotten"},
  {w:"gift",ph:"/ɡɪft/",p:"n.",m:"礼物",col:"birthday gift / gift shop",ex:"I got a gift from my friend.",sy:"gift",tip:"present=礼物（同义）"},
  {w:"giraffe",ph:"/dʒɪˈrɑːf/",p:"n.",m:"长颈鹿",col:"tall giraffe / baby giraffe",ex:"The giraffe has a long neck.",sy:"gi-raffe",tip:"g-i-r-a-f-f-e"},
  {w:"girl",ph:"/ɡɜːl/",p:"n.",m:"女孩",col:"little girl / school girl",ex:"The girl is singing.",sy:"girl",tip:"反义词：boy"},
  {w:"give",ph:"/ɡɪv/",p:"v.",m:"给",col:"give me / give a present",ex:"Give me the book, please.",pt:"gave",sy:"give",tip:"give→gave→given"},
  {w:"glass",ph:"/ɡlɑːs/",p:"n.",m:"玻璃；杯子",col:"a glass of water / broken glass",ex:"Drink a glass of milk.",sy:"glass",tip:"glasses=眼镜"},
  {w:"glove",ph:"/ɡlʌv/",p:"n.",m:"手套",col:"wear gloves / pair of gloves",ex:"Wear gloves in winter.",sy:"glove",tip:"g-l-o-v-e"},
  {w:"glue",ph:"/ɡluː/",p:"n.",m:"胶水",col:"bottle of glue / glue stick",ex:"Use glue to stick the paper.",sy:"glue",tip:"g-l-u-e"},
  {w:"go",ph:"/ɡəʊ/",p:"v.",m:"去",col:"go to school / go home / go away",ex:"Let's go to the park.",pt:"went",sy:"go",tip:"go→went→gone"},
  {w:"goal",ph:"/ɡəʊl/",p:"n.",m:"目标；进球",col:"score a goal / achieve a goal",ex:"He scored a goal!",sy:"goal",tip:"go+al=目标"},
  {w:"goat",ph:"/ɡəʊt/",p:"n.",m:"山羊",col:"mountain goat / baby goat",ex:"The goat is eating grass.",sy:"goat",tip:"g-o-a-t"},
  {w:"good",ph:"/ɡʊd/",p:"adj.",m:"好的",col:"good idea / good job",ex:"You are a good student.",sy:"good",tip:"比较级better，最高级best"},
  {w:"goodbye",ph:"/ɡʊdˈbaɪ/",p:"interj.",m:"再见",col:"say goodbye / wave goodbye",ex:"Goodbye, see you tomorrow!",sy:"good-bye",tip:"bye=再见（缩写）"},
  {w:"grandma",ph:"/ˈɡrænmɑː/",p:"n.",m:"奶奶；外婆",col:"my grandma / Grandma's house",ex:"I love my grandma.",sy:"grand-ma",tip:"grandmother的简称"},
  {w:"grandpa",ph:"/ˈɡrænpɑː/",p:"n.",m:"爷爷；外公",col:"my grandpa / Grandpa and Grandma",ex:"My grandpa tells me stories.",sy:"grand-pa",tip:"grandfather的简称"},
  {w:"grape",ph:"/ɡreɪp/",p:"n.",m:"葡萄",col:"green grapes / grape juice",ex:"I like eating grapes.",sy:"grape",tip:"g-r-a-p-e"},
  {w:"grass",ph:"/ɡrɑːs/",p:"n.",m:"草",col:"green grass / cut the grass",ex:"Don't walk on the grass.",sy:"grass",tip:"grassland=草地"},
  {w:"great",ph:"/ɡreɪt/",p:"adj.",m:"伟大的；很棒",col:"great idea / great job",ex:"That's a great idea!",sy:"great",tip:"great=很棒/伟大"},
  {w:"green",ph:"/ɡriːn/",p:"adj./n.",m:"绿色的；绿色",col:"green tree / green light",ex:"The grass is green.",sy:"green",tip:"g-r-e-e-n"},
  {w:"grey",ph:"/ɡreɪ/",p:"adj./n.",m:"灰色的；灰色",col:"grey clouds / dark grey",ex:"The cat is grey.",sy:"grey",tip:"gray=灰色（美式）"},
  {w:"ground",ph:"/ɡraʊnd/",p:"n.",m:"地面",col:"on the ground / playground",ex:"The ball fell to the ground.",sy:"ground",tip:"playground=操场"},
  {w:"group",ph:"/ɡruːp/",p:"n.",m:"组；群",col:"a group of / group work",ex:"Work in groups of four.",sy:"group",tip:"group=小组"},
  {w:"grow",ph:"/ɡrəʊ/",p:"v.",m:"生长；种植",col:"grow up / grow flowers",ex:"Plants grow in the sun.",pt:"grew",sy:"grow",tip:"grow→grew→grown"},
  {w:"guess",ph:"/ɡes/",p:"v./n.",m:"猜",col:"guess the word / have a guess",ex:"Guess what I have!",pt:"guessed",sy:"guess",tip:"g-u-e-s-s"},
  {w:"guest",ph:"/ɡest/",p:"n.",m:"客人",col:"house guest / special guest",ex:"We have guests for dinner.",sy:"guest",tip:"g-u-e-s-t"},
  {w:"guide",ph:"/ɡaɪd/",p:"n./v.",m:"导游；指引",col:"tour guide / guide book",ex:"The guide showed us around.",pt:"guided",sy:"guide",tip:"guidance=指导"},
  {w:"guitar",ph:"/ɡɪˈtɑː/",p:"n.",m:"吉他",col:"play the guitar / guitar lesson",ex:"He can play the guitar.",sy:"gui-tar",tip:"guitarist=吉他手"},
  {w:"gym",ph:"/dʒɪm/",p:"n.",m:"体育馆；健身房",col:"go to the gym / gym class",ex:"We have gym class on Monday.",sy:"gym",tip:"gymnasium的简称"},
  {w:"habit",ph:"/ˈhæbɪt/",p:"n.",m:"习惯",col:"good habit / bad habit",ex:"Reading is a good habit.",sy:"hab-it",tip:"habitual=习惯性的"},
  {w:"hair",ph:"/heə/",p:"n.",m:"头发",col:"long hair / black hair",ex:"She has long hair.",sy:"hair",tip:"hare=野兔（同音）"},
  {w:"half",ph:"/hɑːf/",p:"n./adj.",m:"一半",col:"half an hour / half past",ex:"It's half past eight.",sy:"half",tip:"a half=一半"},
  {w:"hand",ph:"/hænd/",p:"n.",m:"手",col:"wash hands / by hand",ex:"Wash your hands before eating.",sy:"hand",tip:"handwriting=手写"},
  {w:"happen",ph:"/ˈhæpən/",p:"v.",m:"发生",col:"happen to / what happened",ex:"What happened to you?",pt:"happened",sy:"hap-pen",tip:"hap=机会"},
  {w:"happy",ph:"/ˈhæpi/",p:"adj.",m:"快乐的",col:"feel happy / happy birthday",ex:"I'm very happy today.",sy:"hap-py",tip:"反义词：sad"},
  {w:"hard",ph:"/hɑːd/",p:"adj./adv.",m:"困难的；努力地",col:"hard work / study hard",ex:"The test was hard.",sy:"hard",tip:"hard=困难/坚硬"},
  {w:"hat",ph:"/hæt/",p:"n.",m:"帽子",col:"winter hat / wear a hat",ex:"Put on your hat.",sy:"hat",tip:"cap=棒球帽"},
  {w:"have",ph:"/hæv/",p:"v.",m:"有；吃",col:"have a pet / have breakfast",ex:"I have a cat.",pt:"had",sy:"have",tip:"have→had→had"},
  {w:"head",ph:"/hed/",p:"n.",m:"头",col:"head teacher / shake head",ex:"She has a big head.",sy:"head",tip:"headache=头痛"},
  {w:"hear",ph:"/hɪə/",p:"v.",m:"听见",col:"hear a sound / hear from",ex:"I can hear the music.",pt:"heard",sy:"hear",tip:"hear→heard→heard"},
  {w:"heart",ph:"/hɑːt/",p:"n.",m:"心脏；心",col:"kind heart / learn by heart",ex:"My heart beats fast.",sy:"heart",tip:"h-e-a-r-t"},
  {w:"heavy",ph:"/ˈhevi/",p:"adj.",m:"重的",col:"heavy bag / heavy rain",ex:"The box is too heavy.",sy:"heav-y",tip:"反义词：light"},
  {w:"hello",ph:"/həˈləʊ/",p:"interj.",m:"你好",col:"say hello / hello everyone",ex:"Hello, my name is Tom.",sy:"hel-lo",tip:"hi=你好（更随意）"},
  {w:"help",ph:"/help/",p:"v./n.",m:"帮助",col:"help me / help yourself",ex:"Can you help me?",pt:"helped",sy:"help",tip:"helpful=有帮助的"},
  {w:"hen",ph:"/hen/",p:"n.",m:"母鸡",col:"hen and eggs / mother hen",ex:"The hen laid an egg.",sy:"hen",tip:"rooster=公鸡"},
  {w:"here",ph:"/hɪə/",p:"adv.",m:"这里",col:"here you are / come here",ex:"Here you are.",sy:"here",tip:"反义词：there"},
  {w:"hide",ph:"/haɪd/",p:"v.",m:"躲藏",col:"hide and seek / hide in",ex:"Let's play hide and seek.",pt:"hid",sy:"hide",tip:"hid→hid→hidden"},
  {w:"high",ph:"/haɪ/",p:"adj./adv.",m:"高的",col:"high mountain / fly high",ex:"The mountain is very high.",sy:"high",tip:"反义词：low"},
  {w:"hill",ph:"/hɪl/",p:"n.",m:"小山",col:"top of the hill / green hill",ex:"We climbed the hill.",sy:"hill",tip:"mountain=大山（更高）"},
  {w:"holiday",ph:"/ˈhɒlədeɪ/",p:"n.",m:"假日；假期",col:"school holiday / holiday trip",ex:"Summer holiday is coming!",sy:"hol-i-day",tip:"holy+day=假日"},
  {w:"home",ph:"/həʊm/",p:"n./adv.",m:"家；回家",col:"at home / go home",ex:"I stay at home today.",sy:"home",tip:"homework=作业"},
  {w:"hope",ph:"/həʊp/",p:"v./n.",m:"希望",col:"hope to / I hope so",ex:"I hope you can come.",pt:"hoped",sy:"hope",tip:"hopeful=有希望的"},
  {w:"horse",ph:"/hɔːs/",p:"n.",m:"马",col:"ride a horse / black horse",ex:"The horse runs fast.",sy:"horse",tip:"h-o-r-s-e"},
  {w:"hospital",ph:"/ˈhɒspɪtl/",p:"n.",m:"医院",col:"in hospital / go to hospital",ex:"The doctor works in the hospital.",sy:"hos-pi-tal",tip:"Doctor在hospital工作"},
  {w:"hot",ph:"/hɒt/",p:"adj.",m:"热的；辣的",col:"hot water / hot weather",ex:"It's hot in summer.",sy:"hot",tip:"反义词：cold"},
  {w:"hotel",ph:"/həʊˈtel/",p:"n.",m:"旅馆",col:"stay in a hotel / five-star hotel",ex:"We stayed in a hotel.",sy:"ho-tel",tip:"h-o-t-e-l"},
  {w:"hour",ph:"/ˈaʊə/",p:"n.",m:"小时",col:"half an hour / one hour",ex:"I waited for an hour.",sy:"hour",tip:"our=我们的（同音）"},
  {w:"house",ph:"/haʊs/",p:"n.",m:"房子",col:"at my house / house work",ex:"My house has a garden.",sy:"house",tip:"home=家（更温馨）"},
  {w:"how",ph:"/haʊ/",p:"adv.",m:"如何；多少",col:"how many / how old / how much",ex:"How are you today?",sy:"how",tip:"how=怎样"},
  {w:"hug",ph:"/hʌɡ/",p:"v./n.",m:"拥抱",col:"give a hug / hug me",ex:"Mom gave me a hug.",pt:"huged",sy:"hug",tip:"hug=拥抱"},
  {w:"huge",ph:"/hjuːdʒ/",p:"adj.",m:"巨大的",col:"huge house / huge dog",ex:"The elephant is huge.",sy:"huge",tip:"反义词：tiny"},
  {w:"hungry",ph:"/ˈhʌŋɡri/",p:"adj.",m:"饿的",col:"feel hungry / hungry child",ex:"I'm very hungry.",sy:"hun-gry",tip:"hunger=饥饿"},
  {w:"hurry",ph:"/ˈhʌri/",p:"v./n.",m:"赶紧",col:"hurry up / in a hurry",ex:"Hurry up! We're late.",pt:"hurried",sy:"hur-ry",tip:"hurricane=飓风"},
  {w:"hurt",ph:"/hɜːt/",p:"v.",m:"受伤；疼痛",col:"hurt my leg / it hurts",ex:"My leg hurts.",pt:"hurt",sy:"hurt",tip:"hurt→hurt→hurt"},
  {w:"husband",ph:"/ˈhʌzbənd/",p:"n.",m:"丈夫",col:"husband and wife",ex:"My husband is a teacher.",sy:"hus-band",tip:"wife=妻子"},
  {w:"ice",ph:"/aɪs/",p:"n.",m:"冰",col:"ice cream / ice cold",ex:"The lake is covered with ice.",sy:"ice",tip:"i-c-e"},
  {w:"idea",ph:"/aɪˈdɪə/",p:"n.",m:"主意",col:"good idea / have an idea",ex:"I have a great idea!",sy:"i-de-a",tip:"idea=想法"},
  {w:"important",ph:"/ɪmˈpɔːtnt/",p:"adj.",m:"重要的",col:"important thing / very important",ex:"This is very important.",sy:"im-por-tant",tip:"importance=重要性"},
  {w:"impossible",ph:"/ɪmˈpɒsəbl/",p:"adj.",m:"不可能的",col:"impossible mission",ex:"Nothing is impossible.",sy:"im-pos-si-ble",tip:"im+possible=不可能"},
  {w:"information",ph:"/ˌɪnfəˈmeɪʃn/",p:"n.",m:"信息",col:"useful information / get information",ex:"I need some information.",sy:"in-for-ma-tion",tip:"inform+ation=信息"},
  {w:"inside",ph:"/ɪnˈsaɪd/",p:"prep./adv.",m:"在…里面",col:"inside the box / come inside",ex:"It's warm inside the house.",sy:"in-side",tip:"反义词：outside"},
  {w:"instrument",ph:"/ˈɪnstrəmənt/",p:"n.",m:"乐器；工具",col:"musical instrument / play an instrument",ex:"The guitar is my favourite instrument.",sy:"in-stru-ment",tip:"instrument=工具"},
  {w:"interested",ph:"/ˈɪntrəstɪd/",p:"adj.",m:"感兴趣的",col:"be interested in",ex:"I am interested in science.",sy:"in-ter-est-ed",tip:"interest=兴趣"},
  {w:"interesting",ph:"/ˈɪntrəstɪŋ/",p:"adj.",m:"有趣的",col:"interesting book / sound interesting",ex:"This book is interesting.",sy:"in-ter-est-ing",tip:"interest+ing=有趣的"},
  {w:"Internet",ph:"/ˈɪntənet/",p:"n.",m:"互联网",col:"on the Internet / surf the Internet",ex:"You can find information on the Internet.",sy:"In-ter-net",tip:"net=网"},
  {w:"invent",ph:"/ɪnˈvent/",p:"v.",m:"发明",col:"invent a machine / invent a story",ex:"Who invented the telephone?",pt:"invented",sy:"in-vent",tip:"invention=发明"},
  {w:"island",ph:"/ˈaɪlənd/",p:"n.",m:"岛屿",col:"on the island / treasure island",ex:"We went to a small island.",sy:"is-land",tip:"is+land=岛屿"},
  {w:"jacket",ph:"/ˈdʒækɪt/",p:"n.",m:"夹克",col:"wear a jacket / leather jacket",ex:"Put on your jacket. It's cold.",sy:"jack-et",tip:"jacket=外套"},
  {w:"jam",ph:"/dʒæm/",p:"n.",m:"果酱",col:"strawberry jam / bread and jam",ex:"I like jam on my bread.",sy:"jam",tip:"traffic jam=交通堵塞"},
  {w:"January",ph:"/ˈdʒænjuəri/",p:"n.",m:"一月",col:"in January / January 1st",ex:"New Year's Day is in January.",sy:"Jan-u-a-ry",tip:"Jan是缩写"},
  {w:"job",ph:"/dʒɒb/",p:"n.",m:"工作",col:"do a good job / get a job",ex:"You did a great job!",sy:"job",tip:"good job=做得好"},
  {w:"join",ph:"/dʒɔɪn/",p:"v.",m:"参加",col:"join a club / join us",ex:"Can I join your team?",pt:"joined",sy:"join",tip:"join in=加入"},
  {w:"joke",ph:"/dʒəʊk/",p:"n./v.",m:"笑话",col:"tell a joke / funny joke",ex:"He told me a funny joke.",pt:"joked",sy:"joke",tip:"joke=玩笑"},
  {w:"journey",ph:"/ˈdʒɜːni/",p:"n.",m:"旅程",col:"long journey / bus journey",ex:"The journey took three hours.",sy:"jour-ney",tip:"journey=旅行"},
  {w:"juice",ph:"/dʒuːs/",p:"n.",m:"果汁",col:"orange juice / apple juice",ex:"I'd like a glass of juice.",sy:"juice",tip:"j-u-i-c-e"},
  {w:"July",ph:"/dʒuˈlaɪ/",p:"n.",m:"七月",col:"in July / July 4th",ex:"Summer holiday starts in July.",sy:"Ju-ly",tip:"Jul是缩写"},
  {w:"jump",ph:"/dʒʌmp/",p:"v.",m:"跳",col:"jump high / jump rope",ex:"The cat can jump very high.",pt:"jumped",sy:"jump",tip:"jump=跳跃"},
  {w:"June",ph:"/dʒuːn/",p:"n.",m:"六月",col:"in June / June 1st",ex:"Children's Day is in June.",sy:"June",tip:"Jun是缩写"},
  {w:"jungle",ph:"/ˈdʒʌŋɡl/",p:"n.",m:"丛林",col:"in the jungle / jungle animal",ex:"Tigers live in the jungle.",sy:"jun-gle",tip:"j-u-n-g-l-e"},
  {w:"just",ph:"/dʒʌst/",p:"adv.",m:"刚刚；只是",col:"just now / just a minute",ex:"I just finished my homework.",sy:"just",tip:"just=恰好/刚刚"},
  {w:"kangaroo",ph:"/ˌkæŋɡəˈruː/",p:"n.",m:"袋鼠",col:"baby kangaroo / jump like a kangaroo",ex:"Kangaroos jump very far.",sy:"kan-ga-roo",tip:"来自澳大利亚的动物"},
  {w:"keep",ph:"/kiːp/",p:"v.",m:"保持；保留",col:"keep warm / keep a secret",ex:"Please keep quiet.",pt:"kept",sy:"keep",tip:"keep→kept→kept"},
  {w:"key",ph:"/kiː/",p:"n.",m:"钥匙；关键",col:"key to the door / key word",ex:"I lost my key.",sy:"key",tip:"keyboard=键盘"},
  {w:"kick",ph:"/kɪk/",p:"v.",m:"踢",col:"kick a ball / kick off",ex:"He kicked the ball.",pt:"kicked",sy:"kick",tip:"kick=踢"},
  {w:"kid",ph:"/kɪd/",p:"n.",m:"孩子",col:"little kid / school kid",ex:"The kids are playing.",sy:"kid",tip:"kid=孩子（口语）"},
  {w:"kind",ph:"/kaɪnd/",p:"adj./n.",m:"善良的；种类",col:"kind person / different kinds",ex:"She is very kind.",sy:"kind",tip:"kind-hearted=善良的"},
  {w:"king",ph:"/kɪŋ/",p:"n.",m:"国王",col:"king and queen / lion king",ex:"The king lives in a castle.",sy:"king",tip:"queen=女王/王后"},
  {w:"kiss",ph:"/kɪs/",p:"v./n.",m:"吻",col:"kiss me / give a kiss",ex:"Good night, kiss me.",pt:"kissed",sy:"kiss",tip:"kiss=亲吻"},
  {w:"kitchen",ph:"/ˈkɪtʃɪn/",p:"n.",m:"厨房",col:"in the kitchen / kitchen table",ex:"Mom is cooking in the kitchen.",sy:"kitch-en",tip:"kitchen=厨房"},
  {w:"kite",ph:"/kaɪt/",p:"n.",m:"风筝",col:"fly a kite / kite flying",ex:"Let's fly a kite.",sy:"kite",tip:"k-i-t-e"},
  {w:"knee",ph:"/niː/",p:"n.",m:"膝盖",col:"hurt my knee / fall on knees",ex:"I hurt my knee.",sy:"knee",tip:"k不发音"},
  {w:"knife",ph:"/naɪf/",p:"n.",m:"刀",col:"knife and fork / cut with a knife",ex:"Be careful with the knife.",sy:"knife",tip:"k不发音"},
  {w:"knock",ph:"/nɒk/",p:"v.",m:"敲",col:"knock on the door / knock at",ex:"Please knock before entering.",pt:"knocked",sy:"knock",tip:"k不发音"},
  {w:"know",ph:"/nəʊ/",p:"v.",m:"知道",col:"know about / know how to",ex:"I know the answer.",pt:"knew",sy:"know",tip:"k不发音"},
  {w:"lady",ph:"/ˈleɪdi/",p:"n.",m:"女士",col:"ladies and gentlemen / old lady",ex:"She is a nice old lady.",sy:"la-dy",tip:"反义词：gentleman"},
  {w:"lake",ph:"/leɪk/",p:"n.",m:"湖",col:"by the lake / lake view",ex:"We swim in the lake.",sy:"lake",tip:"l-a-k-e"},
  {w:"lamp",ph:"/læmp/",p:"n.",m:"台灯",col:"turn on the lamp / table lamp",ex:"Turn on the lamp, please.",sy:"lamp",tip:"lamp=灯"},
  {w:"language",ph:"/ˈlæŋɡwɪdʒ/",p:"n.",m:"语言",col:"foreign language / body language",ex:"English is a useful language.",sy:"lan-guage",tip:"lang=舌头/语言"},
  {w:"large",ph:"/lɑːdʒ/",p:"adj.",m:"大的",col:"large room / large size",ex:"The house is very large.",sy:"large",tip:"反义词：small"},
  {w:"last",ph:"/lɑːst/",p:"adj./v.",m:"最后的；持续",col:"last week / last for",ex:"This is the last one.",pt:"lasted",sy:"last",tip:"反义词：first"},
  {w:"late",ph:"/leɪt/",p:"adj./adv.",m:"迟的",col:"be late / arrive late",ex:"Don't be late for school.",sy:"late",tip:"later=后来"},
  {w:"laugh",ph:"/lɑːf/",p:"v./n.",m:"笑",col:"laugh at / laugh out loud",ex:"The joke made me laugh.",pt:"laughed",sy:"laugh",tip:"反义词：cry"},
  {w:"lay",ph:"/leɪ/",p:"v.",m:"放置；下蛋",col:"lay down / lay an egg",ex:"The hen laid an egg.",pt:"laid",sy:"lay",tip:"lay→laid→laid"},
  {w:"lazy",ph:"/ˈleɪzi/",p:"adj.",m:"懒惰的",col:"lazy cat / too lazy",ex:"Don't be lazy.",sy:"la-zy",tip:"反义词：hard-working"},
  {w:"lead",ph:"/liːd/",p:"v.",m:"带领",col:"lead the way / lead a team",ex:"Our teacher leads the class.",pt:"led",sy:"lead",tip:"leader=领导者"},
  {w:"leaf",ph:"/liːf/",p:"n.",m:"叶子",col:"green leaves / autumn leaves",ex:"The leaves are falling.",sy:"leaf",tip:"复数：leaves"},
  {w:"learn",ph:"/lɜːn/",p:"v.",m:"学习",col:"learn English / learn about",ex:"I want to learn to swim.",pt:"learned/learnt",sy:"learn",tip:"learner=学习者"},
  {w:"leave",ph:"/liːv/",p:"v.",m:"离开",col:"leave home / leave school",ex:"I leave for school at 7:30.",pt:"left",sy:"leave",tip:"leave→left→left"},
  {w:"left",ph:"/left/",p:"adj./n.",m:"左边",col:"on the left / left hand",ex:"Turn left at the shop.",sy:"left",tip:"反义词：right"},
  {w:"leg",ph:"/leɡ/",p:"n.",m:"腿",col:"long legs / break a leg",ex:"The spider has eight legs.",sy:"leg",tip:"l-e-g"},
  {w:"lemon",ph:"/ˈlemən/",p:"n.",m:"柠檬",col:"lemon juice / lemon tree",ex:"The lemon tastes sour.",sy:"lem-on",tip:"l-e-m-o-n"},
  {w:"lesson",ph:"/ˈlesn/",p:"n.",m:"课；教训",col:"have a lesson / learn a lesson",ex:"We have an English lesson.",sy:"les-son",tip:"lesson=课程/教训"},
  {w:"letter",ph:"/ˈletə/",p:"n.",m:"信；字母",col:"write a letter / capital letter",ex:"I wrote a letter to my friend.",sy:"let-ter",tip:"letter=字母/信"},
  {w:"library",ph:"/ˈlaɪbrəri/",p:"n.",m:"图书馆",col:"in the library / school library",ex:"I borrow books from the library.",sy:"li-bra-ry",tip:"librarian=图书管理员"},
  {w:"lie",ph:"/laɪ/",p:"v.",m:"躺；说谎",col:"lie down / tell a lie",ex:"Don't lie on the sofa.",pt:"lay",sy:"lie",tip:"lie→lay→lain"},
  {w:"light",ph:"/laɪt/",p:"n./adj.",m:"光；轻的",col:"turn on the light / light bag",ex:"The box is very light.",sy:"light",tip:"反义词：dark/heavy"},
  {w:"like",ph:"/laɪk/",p:"v./prep.",m:"喜欢；像",col:"like music / look like",ex:"I like to draw.",pt:"liked",sy:"like",tip:"unlike=不像"},
  {w:"line",ph:"/laɪn/",p:"n.",m:"线；排队",col:"draw a line / stand in line",ex:"Please stand in line.",sy:"line",tip:"line=线条/队列"},
  {w:"lion",ph:"/ˈlaɪən/",p:"n.",m:"狮子",col:"lion king / brave lion",ex:"The lion is the king of animals.",sy:"li-on",tip:"l-i-o-n"},
  {w:"list",ph:"/lɪst/",p:"n.",m:"列表",col:"shopping list / word list",ex:"Make a list of things to do.",sy:"list",tip:"l-i-s-t"},
  {w:"listen",ph:"/ˈlɪsn/",p:"v.",m:"听",col:"listen to music / listen carefully",ex:"Listen to the teacher.",pt:"listened",sy:"lis-ten",tip:"t不发音"},
  {w:"little",ph:"/ˈlɪtl/",p:"adj.",m:"小的；少的",col:"little girl / a little",ex:"I have a little dog.",sy:"lit-tle",tip:"反义词：big/large"},
  {w:"live",ph:"/lɪv/",p:"v.",m:"居住；活着",col:"live in / live with",ex:"I live in Beijing.",pt:"lived",sy:"live",tip:"life=生命（名词）"},
  {w:"lizard",ph:"/ˈlɪzəd/",p:"n.",m:"蜥蜴",col:"green lizard / little lizard",ex:"The lizard is on the wall.",sy:"liz-ard",tip:"lizard=蜥蜴"},
  {w:"long",ph:"/lɒŋ/",p:"adj.",m:"长的",col:"long hair / long time",ex:"The snake is very long.",sy:"long",tip:"反义词：short"},
  {w:"look",ph:"/lʊk/",p:"v.",m:"看",col:"look at / look for / look after",ex:"Look at the board.",pt:"looked",sy:"look",tip:"look=看（强调动作）"},
  {w:"lose",ph:"/luːz/",p:"v.",m:"丢失；输",col:"lose a game / lose my keys",ex:"Don't lose your pen.",pt:"lost",sy:"lose",tip:"lose→lost→lost"},
  {w:"lot",ph:"/lɒt/",p:"n.",m:"很多",col:"a lot of / lots of",ex:"I have a lot of books.",sy:"lot",tip:"a lot=很/非常"},
  {w:"loud",ph:"/laʊd/",p:"adj.",m:"大声的",col:"loud music / speak loud",ex:"The music is too loud.",sy:"loud",tip:"反义词：quiet"},
  {w:"love",ph:"/lʌv/",p:"v./n.",m:"爱",col:"love my family / I love you",ex:"I love my mom.",pt:"loved",sy:"love",tip:"lovely=可爱的"},
  {w:"lovely",ph:"/ˈlʌvli/",p:"adj.",m:"可爱的；美好的",col:"lovely day / lovely girl",ex:"What a lovely day!",sy:"love-ly",tip:"love+ly=可爱的"},
  {w:"luck",ph:"/lʌk/",p:"n.",m:"运气",col:"good luck / bad luck",ex:"Good luck with your test!",sy:"luck",tip:"lucky=幸运的"},
  {w:"lunch",ph:"/lʌntʃ/",p:"n.",m:"午餐",col:"have lunch / lunch time",ex:"We have lunch at school.",sy:"lunch",tip:"breakfast+lunch+dinner"},
  {w:"machine",ph:"/məˈʃiːn/",p:"n.",m:"机器",col:"washing machine / coffee machine",ex:"The machine can make coffee.",sy:"ma-chine",tip:"machinery=机械"},
  {w:"mad",ph:"/mæd/",p:"adj.",m:"生气的；疯狂的",col:"go mad / feel mad",ex:"Don't be mad at me.",sy:"mad",tip:"angry=生气的"},
  {w:"magazine",ph:"/ˌmæɡəˈziːn/",p:"n.",m:"杂志",col:"read a magazine / fashion magazine",ex:"I like reading magazines.",sy:"ma-ga-zine",tip:"magazine=杂志"},
  {w:"magic",ph:"/ˈmædʒɪk/",p:"n./adj.",m:"魔法；有魔力的",col:"magic show / magic trick",ex:"The magician did a magic trick.",sy:"ma-gic",tip:"magician=魔术师"},
  {w:"make",ph:"/meɪk/",p:"v.",m:"做；制造",col:"make a cake / make a model",ex:"Let's make a card.",pt:"made",sy:"make",tip:"make→made→made"},
  {w:"man",ph:"/mæn/",p:"n.",m:"男人",col:"old man / young man",ex:"The man is my father.",sy:"man",tip:"复数：men"},
  {w:"many",ph:"/ˈmeni/",p:"adj./pron.",m:"许多",col:"many books / how many",ex:"How many pencils do you have?",sy:"ma-ny",tip:"many修饰可数名词"},
  {w:"map",ph:"/mæp/",p:"n.",m:"地图",col:"world map / treasure map",ex:"Look at the map of China.",sy:"map",tip:"m-a-p"},
  {w:"March",ph:"/mɑːtʃ/",p:"n.",m:"三月",col:"in March / March 8th",ex:"Spring starts in March.",sy:"March",tip:"Mar是缩写"},
  {w:"mark",ph:"/mɑːk/",p:"n./v.",m:"标记；分数",col:"good marks / question mark",ex:"I got full marks!",pt:"marked",sy:"mark",tip:"mark=记号/分数"},
  {w:"market",ph:"/ˈmɑːkɪt/",p:"n.",m:"市场",col:"market day / fruit market",ex:"Mom goes to the market.",sy:"mar-ket",tip:"supermarket=超市"},
  {w:"matter",ph:"/ˈmætə/",p:"n./v.",m:"事情；要紧",col:"What's the matter? / it doesn't matter",ex:"What's the matter with you?",pt:"mattered",sy:"mat-ter",tip:"matter=事情/要紧"},
  {w:"may",ph:"/meɪ/",p:"modal v.",m:"可以；可能",col:"May I...? / It may rain.",ex:"May I come in?",sy:"may",tip:"maybe=也许"},
  {w:"May",ph:"/meɪ/",p:"n.",m:"五月",col:"in May / May Day",ex:"My birthday is in May.",sy:"May",tip:"May=五月"},
  {w:"maybe",ph:"/ˈmeɪbi/",p:"adv.",m:"也许",col:"maybe later / maybe not",ex:"Maybe it will rain today.",sy:"may-be",tip:"may+be=也许"},
  {w:"mean",ph:"/miːn/",p:"v.",m:"意思是",col:"What does it mean? / meaning",ex:"What does this word mean?",pt:"meant",sy:"mean",tip:"meaning=意思"},
  {w:"meat",ph:"/miːt/",p:"n.",m:"肉",col:"fresh meat / meat and vegetables",ex:"I don't eat meat.",sy:"meat",tip:"meat=肉（不可数）"},
  {w:"medicine",ph:"/ˈmedsn/",p:"n.",m:"药",col:"take medicine / medicine bottle",ex:"Take this medicine three times a day.",sy:"me-di-cine",tip:"doctor=医生"},
  {w:"meet",ph:"/miːt/",p:"v.",m:"遇见",col:"meet you / nice to meet you",ex:"Nice to meet you!",pt:"met",sy:"meet",tip:"meet→met→met"},
  {w:"melon",ph:"/ˈmelən/",p:"n.",m:"瓜",col:"watermelon / sweet melon",ex:"Watermelon is my favourite fruit in summer.",sy:"mel-on",tip:"water+melon=西瓜"},
  {w:"memory",ph:"/ˈmeməri/",p:"n.",m:"记忆；回忆",col:"good memory / happy memories",ex:"I have good memories of school.",sy:"me-mo-ry",tip:"memorize=记住"},
  {w:"mend",ph:"/mend/",p:"v.",m:"修理",col:"mend a toy / mend the chair",ex:"Dad mended my bike.",pt:"mended",sy:"mend",tip:"repair=修理（同义）"},
  {w:"menu",ph:"/ˈmenjuː/",p:"n.",m:"菜单",col:"read the menu / order from menu",ex:"Let's look at the menu.",sy:"me-nu",tip:"m-e-n-u"},
  {w:"message",ph:"/ˈmesɪdʒ/",p:"n.",m:"消息",col:"leave a message / text message",ex:"Please leave a message.",sy:"mes-sage",tip:"text message=短信"},
  {w:"milk",ph:"/mɪlk/",p:"n.",m:"牛奶",col:"cold milk / milk and sugar",ex:"I drink milk every day.",sy:"milk",tip:"milky=牛奶的"},
  {w:"mind",ph:"/maɪnd/",p:"n./v.",m:"头脑；介意",col:"change your mind / never mind",ex:"Never mind, try again.",pt:"minded",sy:"mind",tip:"never mind=没关系"},
  {w:"minute",ph:"/ˈmɪnɪt/",p:"n.",m:"分钟",col:"one minute / wait a minute",ex:"Wait a minute, please.",sy:"min-ute",tip:"min是缩写"},
  {w:"mirror",ph:"/ˈmɪrə/",p:"n.",m:"镜子",col:"look in the mirror / rear mirror",ex:"She looks at herself in the mirror.",sy:"mir-ror",tip:"mi-rror"},
  {w:"miss",ph:"/mɪs/",p:"v.",m:"想念；错过",col:"miss you / miss the bus",ex:"I miss my friend.",pt:"missed",sy:"miss",tip:"Miss=小姐"},
  {w:"mistake",ph:"/mɪˈsteɪk/",p:"n.",m:"错误",col:"make a mistake / correct mistakes",ex:"Don't be afraid of mistakes.",sy:"mis-take",tip:"mis+take=拿错=错误"},
  {w:"mix",ph:"/mɪks/",p:"v.",m:"混合",col:"mix colours / mix together",ex:"Mix red and blue to get purple.",pt:"mixed",sy:"mix",tip:"mixture=混合物"},
  {w:"model",ph:"/ˈmɒdl/",p:"n.",m:"模型；模特",col:"model plane / fashion model",ex:"I made a model car.",sy:"mod-el",tip:"model=模型/楷模"},
  {w:"Monday",ph:"/ˈmʌndeɪ/",p:"n.",m:"星期一",col:"on Monday / Monday morning",ex:"Monday is the first school day.",sy:"Mon-day",tip:"Mon是缩写"},
];


